modLoader = "javafml"
loaderVersion = "[39,)"
license = "All rights reserved"
[[mods]]
logoFile = "enigmatic_tech.png"
modId = "enigmatic_tech"
version = "${file.jarVersion}"
displayName = "Enigmatic Tech"
authors = "Sammy;"
description = '''
An work in progress high level technology mod.
'''
[[dependencies.enigmatic_tech]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"