modLoader = "javafml"
loaderVersion = "[39,)"
license = "All rights reserved"
[[mods]]
logoFile = "icon.png"
modId = "enigmatic_tech"
version = "${file.jarVersion}"
displayName = "Enigmatic Tech"
authors = "Sammy;"
description = '''
A work in progress high level technology mod.
'''
[[dependencies.enigmatic_tech]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.enigmatic_tech]]
modId="lodestone"
mandatory=true
versionRange="[FORGE-1.18.2-1.3,)"
ordering="AFTER"
side="BOTH"